PR-581 Update from upstream v0.15.0
mdblp/shoreline pull request #20
Opened 2019-08-28 15:52 UTC by yvon-dblg

See https://diabeloop.atlassian.net/browse/PT-581

`/!\` Still use the go-common in a dev branch (feature/pt582-0.4.1)

2019-10-04 14:10 UTC, CedricPerotto requested changes
The Dockerfile differs widely from from the tidepool version without any reason for me (except the ENV GO111MODULE that should be documented for next updates from Tidepool). 
Also a log trace in the mongo client that may be too verbose (email/name/id in the trace).

Apart from these two points, everything looks ok. 
Waiting for go-common revision before merging.

2019-10-04 14:10 UTC, CedricPerotto commented on Dockerfile
> +WORKDIR /go/src/github.com/mdblp/shoreline
I don't see why we have to change all path in docker container.  Less changes, less conflicts in the future.
```suggestion
WORKDIR /go/src/github.com/tidepool-org/shoreline
```

2019-10-04 14:10 UTC, CedricPerotto commented on Dockerfile
> +    adduser -D mdblp
Same for the user
```suggestion
    adduser -D tidepool
```

2019-10-04 14:10 UTC, CedricPerotto commented on Dockerfile
> +WORKDIR /home/mdblp
```suggestion
WORKDIR /home/tidepool
```

2019-10-04 14:10 UTC, CedricPerotto commented on Dockerfile
> +USER mdblp
```suggestion
USER tidepool
```

2019-10-04 14:10 UTC, CedricPerotto commented on Dockerfile
> +COPY --from=development --chown=mdblp /go/src/github.com/mdblp/shoreline/dist/shoreline .
```suggestion
COPY --from=development --chown=tidepool /go/src/github.com/tidepool-org/shoreline/dist/shoreline .
```

2019-10-04 14:10 UTC, CedricPerotto commented on Dockerfile
> +ENV GO111MODULE on
Could you comment the DockerFile to explain why we have to set this environment in mdblp context and when we won't need it any more (Go 1.13 if roadmap is accurate) ?

2019-10-04 14:10 UTC, CedricPerotto commented on user/mongoStoreClient.go
> +		log.Printf("no users found: query: (Id = %v) OR (Name ~= %v) OR (Emails IN %v)", user.Id, user.Username, user.Emails)
Not sur if logging id, name and emails when request fails is compliant with our personal data policy...

2019-10-04 15:09 UTC, yvon-dblg commented on Dockerfile
> +WORKDIR /go/src/github.com/mdblp/shoreline
When using GO111MODULE with github.com/tidepool-org/shoreline it fetch the tidepool project...

2019-10-04 15:10 UTC, yvon-dblg commented on Dockerfile
> +    adduser -D mdblp
For the other change, I agree, it just seems cool to have a user mdblp instead of tidepool ^^

2019-10-04 15:12 UTC, yvon-dblg commented on user/mongoStoreClient.go
> +		log.Printf("no users found: query: (Id = %v) OR (Name ~= %v) OR (Emails IN %v)", user.Id, user.Username, user.Emails)
It is a tidepool change which I left it at is.
Maybe ask someone else to be sure ?

2019-10-04 15:30 UTC, CedricPerotto commented on Dockerfile
> +WORKDIR /go/src/github.com/mdblp/shoreline
Just tested it locally, it doesn't fetch the github.com/tidepool-org/shoreline repository.

2019-10-08 10:16 UTC, yvon-dblg commented on Dockerfile
> +WORKDIR /go/src/github.com/mdblp/shoreline
Also we don't need anymore the fix travis folder:

> `# fix travis working folder (see http://www.ruflin.com/2015/08/13/fix-for-travis-ci-failure-in-forked-golang-repositories/)`
which was present in the .travis.yml file.

2019-10-08 12:00 UTC, yvon-dblg commented
See PR https://github.com/mdblp/shoreline/pull/21

2019-10-08 12:00 UTC, closed without merging