PT-1026 max login counter
mdblp/shoreline pull request #27
Opened 2020-02-10 12:23 UTC by yvon-dblg

2020-02-26 16:09 UTC, ydrisR requested changes
Nice work globally :)
I propose to change a couple of variable names. 

One problematic changed (at least from my point of view) if the changes on the HTTP return codes. I don't think there is a need to change the current behaviour.
Also we should be carefull about what is logged by the service: should we log user names and other personal infos in the log files? Probably something to discuss as a team.

2020-02-26 16:09 UTC, ydrisR commented on env.sh
> +        "delayToAllowNewLoginAttempt": 10,
```suggestion
        "delayBeforeNextLoginAttempt": 10,
```

2020-02-26 16:09 UTC, ydrisR commented on shoreline.go
> +	config.User.DelayToAllowNewLoginAttempt = 10 // 10 minutes
```suggestion
	config.User.DelayBeforeNextLoginAttempt= 10 // 10 minutes
```

2020-02-26 16:09 UTC, ydrisR commented on user/api.go
> +		DelayToAllowNewLoginAttempt int64 `json:"delayToAllowNewLoginAttempt"`
```suggestion
		DelayBeforeNextLoginAttempt int64 `json:"delayBeforeNextLoginAttempt"`
```

2020-02-26 16:09 UTC, ydrisR commented on user/api.go
> +		nInProgress         int
```suggestion
		totalInProgress         int
```

2020-02-26 16:09 UTC, ydrisR commented on user/api.go
> +		userNamesInProgress *list.List
```suggestion
		usersInProgress *list.List
```

2020-02-26 16:09 UTC, ydrisR commented on user/api.go
> +	api.loginLimiter.userNamesInProgress = list.New()
```suggestion
	api.loginLimiter.usersInProgress = list.New()
```

2020-02-26 16:09 UTC, ydrisR commented on user/api.go
> +		a.sendError(res, http.StatusInternalServerError, STATUS_ERR_CREATING_USR, fmt.Sprintf("User '%s' already exists", *newUserDetails.Username))
Why changing this behaviour?

2020-02-26 16:09 UTC, ydrisR commented on user/api.go
> +		a.sendError(res, http.StatusUnauthorized, STATUS_NO_MATCH, STATUS_USER_NOT_FOUND, err)
why changing the returned code here? it is indeed an internal error if the db query fails...

2020-02-26 16:09 UTC, ydrisR commented on user/api.go
> +		a.sendError(res, http.StatusUnauthorized, STATUS_NO_MATCH, fmt.Sprintf("User '%s' have %d matching results", user.Username, len(results)))
Really need to change this log message?

2020-02-26 16:09 UTC, ydrisR commented on user/api.go
> +		nextAttemptTime := time.Now().Add(time.Minute * time.Duration(a.ApiConfig.DelayToAllowNewLoginAttempt))
```suggestion
		nextAttemptTime := time.Now().Add(time.Minute * time.Duration(a.ApiConfig.DelayBeforeNextLoginAttempt))
```

2020-02-26 16:09 UTC, ydrisR commented on user/api_test.go
> +		DelayToAllowNewLoginAttempt: 10,
```suggestion
		DelayBeforeNextLoginAttempt: 10,
```

2020-02-26 16:09 UTC, ydrisR commented on user/api_test.go
> +	nextAttemptTime := time.Now().Add(time.Minute * time.Duration(FAKE_CONFIG.DelayToAllowNewLoginAttempt))
```suggestion
	nextAttemptTime := time.Now().Add(time.Minute * time.Duration(FAKE_CONFIG.DelayBeforeNextLoginAttempt))
```

2020-02-26 16:09 UTC, ydrisR commented on user/helpers.go
> +	a.loginLimiter.nInProgress++
```suggestion
	a.loginLimiter.totalInProgress++
```

2020-02-26 16:09 UTC, ydrisR commented on user/helpers.go
> +	if a.loginLimiter.nInProgress > a.ApiConfig.MaxConcurrentLogin {
```suggestion
	if a.loginLimiter.totalInProgress > a.ApiConfig.MaxConcurrentLogin {
```

2020-02-26 16:44 UTC, yvon-dblg commented on user/api.go
> +		a.sendError(res, http.StatusUnauthorized, STATUS_NO_MATCH, fmt.Sprintf("User '%s' have %d matching results", user.Username, len(results)))
It was to have all logged message on the same pattern.
Should help @CedricPerotto with ELK.

2020-02-26 17:03 UTC, yvon-dblg commented on user/api.go
> +		a.sendError(res, http.StatusInternalServerError, STATUS_ERR_CREATING_USR, fmt.Sprintf("User '%s' already exists", *newUserDetails.Username))
OWASP recommandations, see https://owasp.org/www-project-cheat-sheets/cheatsheets/Authentication_Cheat_Sheet.html

2020-02-26 17:03 UTC, yvon-dblg commented on user/api.go
> +		a.sendError(res, http.StatusUnauthorized, STATUS_NO_MATCH, STATUS_USER_NOT_FOUND, err)
OWASP recommandations, see https://owasp.org/www-project-cheat-sheets/cheatsheets/Authentication_Cheat_Sheet.html

2020-02-27 11:45 UTC, ydrisR approved these changes
LGTM

2020-02-27 11:45 UTC, ydrisR commented on user/api.go
> +		a.sendError(res, http.StatusInternalServerError, STATUS_ERR_CREATING_USR, fmt.Sprintf("User '%s' already exists", *newUserDetails.Username))
I would rather return 403 Forbiden or 401 unauthorized

2020-02-27 11:50 UTC, merged