Automatic generation of openapi documentation
mdblp/shoreline pull request #35
Opened 2020-07-01 14:42 UTC by BigFab

Add automatic generation of the openapi documentation

2020-07-01 15:25 UTC, BigFab commented
Not sure why the build status is not reflected: https://travis-ci.org/github/mdblp/shoreline/builds/703963644
The build on release was done and openapi documentation was pushed to S3: https://s3.console.aws.amazon.com/s3/buckets/com.diabeloop.yourloops.doc/openapi/shoreline/?region=eu-west-1&tab=overview

2020-07-02 17:37 UTC, franck-fourel requested changes
a proposal to remove the dblp thing if needed. 
works like a charm on my side.

2020-07-02 17:37 UTC, franck-fourel commented on buildDoc.sh
> +fi
```suggestion
fi

```

2020-07-02 17:37 UTC, franck-fourel commented on buildDoc.sh
> +    APP_TAG="${APP}-${TRAVIS_TAG}"
```suggestion
    APP_TAG="${APP}-${TRAVIS_TAG/dblp./}"
```
removing the dblp thing

2020-07-07 15:22 UTC, franck-fourel approved these changes
LGTM

2020-07-07 19:29 UTC, merged